### ISSUE TITLE
unistd.h does not exist on windows/visual studio and this causes problems

### ISSUE THREAD

**Issue by harrisjose** [ohmu/node-posix#37]
I've managed to get it working for now by replacing it with io.h as suggested on stackoverflow..but surely there must be a better solution ?

Ive managed to dig around and find that both flex and minGW both have their own unistd.h but have tried any of these.

**Comment by melor** [comment]
This library is meant for operating systems that support the POSIX standard in one way or another. Windows nowadays isn't one of them, so basically: Windows + Visual Stdio are not supported.
