### ISSUE TITLE
swapon

### ISSUE THREAD

**Issue by piranna** [ohmu/node-posix#46]
Add support for `swapon` syscall, and maybe for simmetry also `swapoff`.

**Comment by melor** [comment]
No takers (pull requests), closing.

**Comment by piranna** [comment]
I opened this as reminder if others would willing to work on it or want to discuss it first. I'm open to do a pull-request if you could be able to accept it.

**Comment by melor** [comment]
@piranna A swapon(2)/swapoff(2) pull request would certainly be welcome. We'll just need to make sure it compiles and does not fail tests on platforms that don't have those syscalls i.e. all non-Linux.

**Comment by piranna** [comment]
I've just done a pull-request at #49.
