### ISSUE TITLE
Cannot npm install posix@4.1.0 on Centos6.5

### ISSUE THREAD

**Issue by jimithetulip** [ohmu/node-posix#52]
Failing on npm install on centos6.5

Error: Failed at the posix@4.1.0 install script 'node-gyp rebuild'

> posix@4.1.0 install /home/vagrant/blah/node_modules/posix
> node-gyp rebuild

make: Entering directory `/home/vagrant/blah/node_modules/posix/build'
  CXX(target) Release/obj.target/posix/src/posix.o
../src/posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_update_swap_constants(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/posix.cc:653:78: error: ‘SWAP_FLAG_DISCARD’ was not declared in this scope
     obj->Set(Nan::New<String>("discard").ToLocalChecked(), Nan::New<Integer>(SWAP_FLAG_DISCARD));
                                                                              ^
make: *** [Release/obj.target/posix/src/posix.o] Error 1
make: Leaving directory `/home/vagrant/blah/node_modules/posix/build'

**Comment by melor** [comment]
Fixed in posix@4.1.1
